// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qerekbtwimbxrvijrdce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFlcmVrYnR3aW1ieHJ2aWpyZGNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5ODgzNDcsImV4cCI6MjA3NDU2NDM0N30.kSBz5AmTTE4AWuhKp0gIMyj8q2CSTsdPQJ1zmfExyhU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});